# docker-compose.yml
version: "3.9"
services:
  visa-face-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env          # <-- use a real .env on the server
    ports:
      - "8000:8000"   # change if your app uses another port
    volumes:
      - ./Images:/app/Images   # <-- host Images folder persists container data
    restart: unless-stopped
